/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package program;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import objektumok.LadaGomb;
/**
 *
 * @author SzabóRoland(SZF_2023
 */
public class MainGUI extends javax.swing.JFrame {
    LadaGomb[] ladak;
    Kincseslada k;
    
    
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        k = new Kincseslada();
        initform();
        gombs();
    }
    
    public final void initform(){
        La_visszajelez.setText("");
    }
    
    public final void gombs(){
        String[] feliratok = k.getFeliratok();
        Kincseslada.Szinek[] szinek = k.getSzinek();
        ladak = new LadaGomb[feliratok.length];
        
        for (int i = 0; i < feliratok.length; i++) {
            ladak[i] = new LadaGomb((byte)(i+1), k.getSzinek(szinek[i]), (i*152)+32, 36, "", "");
        }
        
        //Pn_ladak.removeAll();
        
       // Pn_ladak.setLayout(new BorderLayout());
        for (int i = 0; i < ladak.length; i++) {
            LadaGomb lada = ladak[i];
            ladak[i].addActionListener(new ActionListener() {  
                @Override
                public void actionPerformed(ActionEvent e) {
                    if(!k.getKitalalva()){
                        boolean ezaz = k.kitalal(lada.getLadaszam());
                        lada.kinyit(ezaz);
                        La_visszajelez.setText(ezaz ? "Gratulálok! Megtaláltad a kincset." : "Nem ebben a ládában van a kincs.");
                    }
                }
            });
            Pn_ladak.add(ladak[i]);
        }
        Pn_ladak.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pn_ladak = new javax.swing.JPanel();
        La_visszajelez = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pn_ladak.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout Pn_ladakLayout = new javax.swing.GroupLayout(Pn_ladak);
        Pn_ladak.setLayout(Pn_ladakLayout);
        Pn_ladakLayout.setHorizontalGroup(
            Pn_ladakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );
        Pn_ladakLayout.setVerticalGroup(
            Pn_ladakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );

        La_visszajelez.setText("Nem ez a láda rejti a kincset./Gratulálok, megtaláltad a kincset.");

        jLabel1.setText("<html>\n<head>\n<style>\n*{\ndisplay: block;\nmargin: 0px;\npadding: 0px;\n}\nbody{\n/*background-color: brown;\ncolor:  green;*/\n}\n.tabb{\npadding: 0px;\nmargin: 0px;\nmargin-left: 20px;\n}\n</style>\n</head>\n<body>\n<p>Van három láda: Arany, Ezüst, Bronz.</p>\n<p class='tabb'>\n<br>A ládákon van egy-egy állítás, ezek közül csak az egyik igaz.\n<br>Arany: Én rejtem a kincset.\n<br>Ezüst: Nem én rejtem a kincset. \n<br>Bronz: Az arany láda hazudik.\n</p>\n</body>\n</html>");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(Pn_ladak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(La_visszajelez, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pn_ladak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(La_visszajelez)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel La_visszajelez;
    private javax.swing.JPanel Pn_ladak;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
